services:
  backend:
    build: .
    container_name: backend
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      POSTGRES_HOST: ep-shiny-surf-a5tp3fio.us-east-2.aws.neon.tech
      POSTGRES_USER: featuredJobs_owner
      POSTGRES_PASSWORD: yRZMV5YpKx7i
      POSTGRES_DB: featuredJobs

volumes:
  postgres_data: