services:
  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_HOST : ep-shiny-surf-a5tp3fio.us-east-2.aws.neon.tech
      POSTGRES_USER: featuredJobs_owner
      POSTGRES_PASSWORD: yRZMV5YpKx7i
      POSTGRES_DB: featuredJobs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  postgres_data: