services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./
    container_name: backend
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  postgres_data:
